
export const questionsJson = {
    "question1":   "Externship Site Name:",
    "question2":   "Which year did/ will you graduate/ complete your externship?",
    "question3":   "Is/was your externship in the US?",
    "question4":   "If not, where was your externship located?",
    "question5":   "City of Externship?",
    "question6":   "Externship State or Territory?",
    "question7":   "Duration of Externship? (months)",
    "question8":   "Number of days per week?",
    "question9":   "Hours per day?",
    "question10":   "Was compensation provided?",
    "question11":   "Annual Compensation:",
    "question12":   "How was compensation distributed?",
    "question13":   "Does the student get health insurance or other benefits?",
    "question14":   "If yes, could you provide details?",
    "question15":   "How many preceptors do you have?",
    "question16":   "Preceptors and CCC-A",
    "question17":   "Preceptor's background:",
    "question18":   "Feedback style of preceptors - Feedback is provided:",
    "question19":   "How supported did you feel during the externship?",
    "question20":   "The clinic population is mainly:",
    "question21":   "How diverse is the clientele? Check all the racial and ethnic identities seen in the clinic:",
    "question22":   "Predominantly which population is seen in the clinic:",
    "question23":   "How diverse is the clientele? (to the best of your knowledge/ perception):",
    "question24":   "Predominantly which population is seen in the clinic- (to the best of your knowledge/ perception):",
    "question25":   "Does the clinic have rotations for specialties such as vestibular, cochlear implants, etc.",
    "question26":   "Please provide more details about each rotation:",
    "question27":   "Please select which of the following experiences are provided to students:",
    "question28":   "Routine audiological testing (Audiometry + immittance):",
    "question29":   "Hearing aid consultation:",
    "question30":   "Hearing aid fitting:",
    "question31":   "Hearing aid follow up:",
    "question32":   "ABR:",
    "question33":   "Other electrophysiological measures such as ASSR, EcochG:",
    "question34":   "OAEs:",
    "question35":   "CPA:",
    "question36":   "VRA:",
    "question37":   "CAPD testing:",
    "question38":   "Tinnitus evaluation:",
    "question39":   "Tinnitus management:",
    "question40":   "Vestibular testing:",
    "question41":   "Vestibular rehabilitation:",
    "question42":   "CI evaluation:",
    "question43":   "CI activation and follow up:",
    "question44":   "Aural rehabilitation:",
    "question45":   "Group rehabilitation",
    "question46":   "Intra-operative monitoring:",
    "question47":   "How long does the student shadow their preceptor(s)?",
    "question48":   "After what duration are students independent (see patients by themselves without supervisor in the room)?",
    "question49":   "Do students have independent schedules?",
    "question50":   "Number of sites and student placement in each site: Which of the following is true about the site:",
    "question51":   "Are hearing aid technicians or other staff available for support?",
    "question52":   "Which professionals does the clinic routinely collaborate with (daily or multiple times a week)?",
    "question53":   "How often are meetings conducted with inter-professional colleagues?",
    "question54":   "How often are meetings held within the department?",
    "question55":   "What is the extern's expected contribution to the meetings?",
    "question56":   "Are research opportunities available?",
    "question57":   "Is research required?",
    "question58":   "Is there time allotted for research or is it something on top of clinical hours?",
    "question59":   "Research opportunities involve:",
    "question60":   "Is time off provided to attend conferences?",
    "question61":   "Are there continuing education opportunities? Please describe.",
    "question62":   "Where is/was the externship advertised?",
    "question63":   "What is the specialty/most attractive feature of this externship?",
    "question64":   "What are the weaknesses of this externship?",
    "question65":   "Details about lunch breaks:",
    "question66":   "Is the externship site looking to hire students post-externship?",
    "question67":   "What is the cost of living in the area?",
    "question68":   "Is there affordable housing in the area and how is it found?",
    

};